### ISSUE TITLE
Raw assignee and location date

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#25]
I see that we can get raw inventor first and last names from the API, but the raw assignee names (first, last, and organization) and raw location data (city, state, etc.) are not available. It would be great it if we could get the raw data as well for these entities. Would it be possible to add these fields? I noticed that the raw fields are available in your data dumps.

Thanks,
Chris

**Comment by sarahkelley** [comment]
Thanks for the suggestion! We will add this to the list of requests and will let you know when that gets added!
