### ISSUE TITLE
pct_data fields not served in format consistent with other fields

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#27]
Greetings -

It looks like the fields in the pct_data group are not served like fields in other groups. specifically, the fields are not put in an array called "pct_data", as one would expect. Here's an example, where you will see that the fields in other groups (e.g., the wipos and uspcs groups) are given in an array, but pct_data fields are not:

`GET http://www.patentsview.org/api/patents/query?q={"patent_number":"5116621"}&f=["patent_id","pct_102_date","pct_371_date","pct_date","pct_docnumber","pct_doctype","pct_kind","uspc_mainclass_id","uspc_mainclass_title","uspc_sequence","uspc_subclass_id","wipo_field_id","wipo_field_title","wipo_sector_title","wipo_sequence"]&o={"include_subentity_total_counts":false,"matched_subentities_only":true,"page":1,"per_page":25}&s=`

```
{"patents":[{"patent_id":"5116621","uspcs":[{"uspc_mainclass_id":"424","uspc_mainclass_title":"Drug, bio-affecting and body treating compositions","uspc_sequence":"0","uspc_subclass_id":"424\/445"},{"uspc_mainclass_id":"424","uspc_mainclass_title":"Drug, bio-affecting and body treating compositions","uspc_sequence":"1","uspc_subclass_id":"424\/447"},{"uspc_mainclass_id":"424","uspc_mainclass_title":"Drug, bio-affecting and body treating compositions","uspc_sequence":"2","uspc_subclass_id":"424\/448"},{"uspc_mainclass_id":"424","uspc_mainclass_title":"Drug, bio-affecting and body treating compositions","uspc_sequence":"3","uspc_subclass_id":"424\/449"}],"wipos":[{"wipo_field_id":"16","wipo_field_title":"Pharmaceuticals","wipo_sector_title":"Chemistry","wipo_sequence":"0"}],"pct_data":{"pct_102_date":null,"pct_371_date":null,"pct_date":null,"pct_docnumber":null,"pct_doctype":null,"pct_kind":null,"0":{"pct_102_date":null,"pct_371_date":null,"pct_date":null,"pct_docnumber":null,"pct_doctype":null,"pct_kind":null}}}],"count":1,"total_patent_count":1}
```

**Comment by sarvothaman** [comment]
Thanks for bringing this to our attention. This issue should be fixed now.
