### ISSUE TITLE
patents endpoint not behaving as expected

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#28]
(This issue is happening again).

Hi, I'm not sure how many endpoints this issue is impacting, but something is definitely going on with the patents endpoint. For example, at the time of writing this issue, this request is returning no patents (though it should):

http://www.patentsview.org/api/patents/query?q={"_eq":{"inventor_last_name":"chambers"}}&f=["patent_number"]

While this request is returning results as expected: 

http://www.patentsview.org/api/patents/query?q={"_eq":{"inventor_last_name":"jobs"}}&f=["patent_number"]

Note that the second request may be working b/c the query results were cached from an earlier time when the API was not misbehaving.

**Comment by sarahkelley** [comment]
Hello! 
I can't replicate this error - the first query returns results as expect for me. Can you confirm that you are still having this issue?

**Comment by crew102** [comment]
Working now. Thanks!

**Comment by sarahkelley** [comment]
Now I can replicate the issue, the query is not returning the expected results for me either. We will work on debugging this as soon as possible and let you know!

**Comment by crew102** [comment]
This is working now, thanks. I'll leave it up to you whether to close the issue.
