### ISSUE TITLE
Locations endpoint throws 400 error when cpc_sequence field is asked for

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#29]
As noted here https://github.com/ropensci/patentsview/issues/11 by @mustberuss:

> Field validation is done in the api's executeQuery before the database is queried. It throws the 400 error since cpc_sequence is not present in entitySpecs for the location endpoint. It's present for 3 other endpoints (patents, assignees*, inventors*) and other cpc fields are present for the location endpoint.

For example, this GET request returns data:

http://www.patentsview.org/api/locations/query?q={"location_city":"Mount%20Airy"}&f=["location_id","cpc_subgroup_title"]

But this one throws a 400 error:

http://www.patentsview.org/api/locations/query?q={"location_city":"Mount%20Airy"}&f=["cpc_sequence"]

...In which your API returns the following details:

```html
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
```

**Comment by sarvothaman** [comment]
This issue is fixed now!
