### ISSUE TITLE
Inventors endpoint not returning expected data

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#31]
This request, which searches for inventors in Chicago, results in a lot of inventor entities that don't have data (not even a patent numbers, which I believe they should always have, no?): 

http://www.patentsview.org/api/inventors/query?q=%7B%22_and%22:[%7B%22location_city%22:%22Chicago%22%7D,%7B%22location_state%22:%22IL%22%7D]%7D&f=[%22patent_number%22,%22patent_title%22]&o=%7B%22include_subentity_total_counts%22:false,%22matched_subentities_only%22:true,%22page%22:1,%22per_page%22:1000%7D&s=

**Comment by sarvothaman** [comment]
This issue is fixed now!
