### ISSUE TITLE
API server down?

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#32]
Hi there -

I'm not getting any response from the API server. For example:

http://www.patentsview.org/api/patents/query?q={"_gte":{"patent_date":"2007-01-04"}}&f=["patent_number","patent_date"]

**Comment by killahjones** [comment]
Hi Chris - try again? Should be working now.

**Comment by crew102** [comment]
Yep, working now, thanks

**Comment by crew102** [comment]
API not responding to requests again...

**Comment by sarahkelley** [comment]
There was an issue with the API over the weekend due to some encoding changes in the data, but this is resolved now! Thanks for pointing this out!

**Comment by crew102** [comment]
Server's down again...

**Comment by sarahkelley** [comment]
@crew102 We were making few quick changes this afternoon, so it was down for a bit! Everything should be up and running now!

**Comment by crew102** [comment]
Looks like it's still down

**Comment by sarahkelley** [comment]
We are experiencing some technical challenges due to an unanticipated spike in demand - it should be up now and we are working to resolve the issues! We really appreciate your patience!

**Comment by crew102** [comment]
Server is not responding to requests again
