### ISSUE TITLE
API can't handle large field lists anymore?

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#34]
Greetings -

I noticed that the API is throwing errors when I ask for large lists of fields. For example, when I ask the API for data on all of the fields that are supposedly available for the patents endpoint (based on http://www.patentsview.org/api/patent.html#field_list), I get a 500 error:

http://www.patentsview.org/api/patents/query?q=%7B%22patent_number%22:%225116621%22%7D&f=[%22app_country%22,%22app_date%22,%22app_number%22,%22app_type%22,%22appcit_app_number%22,%22appcit_category%22,%22appcit_date%22,%22appcit_kind%22,%22appcit_sequence%22,%22assignee_city%22,%22assignee_country%22,%22assignee_county%22,%22assignee_county_fips%22,%22assignee_first_name%22,%22assignee_first_seen_date%22,%22assignee_id%22,%22assignee_last_name%22,%22assignee_last_seen_date%22,%22assignee_lastknown_city%22,%22assignee_lastknown_country%22,%22assignee_lastknown_latitude%22,%22assignee_lastknown_location_id%22,%22assignee_lastknown_longitude%22,%22assignee_lastknown_state%22,%22assignee_latitude%22,%22assignee_location_id%22,%22assignee_longitude%22,%22assignee_organization%22,%22assignee_sequence%22,%22assignee_state%22,%22assignee_state_fips%22,%22assignee_total_num_inventors%22,%22assignee_total_num_patents%22,%22assignee_type%22,%22cited_patent_category%22,%22cited_patent_date%22,%22cited_patent_kind%22,%22cited_patent_number%22,%22cited_patent_sequence%22,%22cited_patent_title%22,%22citedby_patent_category%22,%22citedby_patent_date%22,%22citedby_patent_kind%22,%22citedby_patent_number%22,%22citedby_patent_title%22,%22cpc_category%22,%22cpc_first_seen_date%22,%22cpc_group_id%22,%22cpc_group_title%22,%22cpc_last_seen_date%22,%22cpc_section_id%22,%22cpc_sequence%22,%22cpc_subgroup_id%22,%22cpc_subgroup_title%22,%22cpc_subsection_id%22,%22cpc_subsection_title%22,%22cpc_total_num_assignees%22,%22cpc_total_num_inventors%22,%22cpc_total_num_patents%22,%22detail_desc_length%22,%22examiner_first_name%22,%22examiner_group%22,%22examiner_id%22,%22examiner_last_name%22,%22examiner_role%22,%22forprior_country%22,%22forprior_date%22,%22forprior_docnumber%22,%22forprior_kind%22,%22forprior_sequence%22,%22govint_contract_award_number%22,%22govint_org_id%22,%22govint_org_level_one%22,%22govint_org_level_three%22,%22govint_org_level_two%22,%22govint_org_name%22,%22govint_raw_statement%22,%22inventor_city%22,%22inventor_country%22,%22inventor_county%22,%22inventor_county_fips%22,%22inventor_first_name%22,%22inventor_first_seen_date%22,%22inventor_id%22,%22inventor_last_name%22,%22inventor_last_seen_date%22,%22inventor_lastknown_city%22,%22inventor_lastknown_country%22,%22inventor_lastknown_latitude%22,%22inventor_lastknown_location_id%22,%22inventor_lastknown_longitude%22,%22inventor_lastknown_state%22,%22inventor_latitude%22,%22inventor_location_id%22,%22inventor_longitude%22,%22inventor_sequence%22,%22inventor_state%22,%22inventor_state_fips%22,%22inventor_total_num_patents%22,%22ipc_action_date%22,%22ipc_class%22,%22ipc_classification_data_source%22,%22ipc_classification_value%22,%22ipc_first_seen_date%22,%22ipc_last_seen_date%22,%22ipc_main_group%22,%22ipc_section%22,%22ipc_sequence%22,%22ipc_subclass%22,%22ipc_subgroup%22,%22ipc_symbol_position%22,%22ipc_total_num_assignees%22,%22ipc_total_num_inventors%22,%22ipc_version_indicator%22,%22lawyer_first_name%22,%22lawyer_first_seen_date%22,%22lawyer_id%22,%22lawyer_last_name%22,%22lawyer_last_seen_date%22,%22lawyer_organization%22,%22lawyer_sequence%22,%22lawyer_total_num_assignees%22,%22lawyer_total_num_inventors%22,%22lawyer_total_num_patents%22,%22nber_category_id%22,%22nber_category_title%22,%22nber_first_seen_date%22,%22nber_last_seen_date%22,%22nber_subcategory_id%22,%22nber_subcategory_title%22,%22nber_total_num_assignees%22,%22nber_total_num_inventors%22,%22nber_total_num_patents%22,%22patent_abstract%22,%22patent_average_processing_time%22,%22patent_date%22,%22patent_firstnamed_assignee_city%22,%22patent_firstnamed_assignee_country%22,%22patent_firstnamed_assignee_id%22,%22patent_firstnamed_assignee_latitude%22,%22patent_firstnamed_assignee_location_id%22,%22patent_firstnamed_assignee_longitude%22,%22patent_firstnamed_assignee_state%22,%22patent_firstnamed_inventor_city%22,%22patent_firstnamed_inventor_country%22,%22patent_firstnamed_inventor_id%22,%22patent_firstnamed_inventor_latitude%22,%22patent_firstnamed_inventor_location_id%22,%22patent_firstnamed_inventor_longitude%22,%22patent_firstnamed_inventor_state%22,%22patent_kind%22,%22patent_num_cited_by_us_patents%22,%22patent_num_claims%22,%22patent_num_combined_citations%22,%22patent_num_foreign_citations%22,%22patent_num_us_application_citations%22,%22patent_num_us_patent_citations%22,%22patent_number%22,%22patent_processing_time%22,%22patent_title%22,%22patent_type%22,%22patent_year%22,%22pct_102_date%22,%22pct_371_date%22,%22pct_date%22,%22pct_docnumber%22,%22pct_doctype%22,%22pct_kind%22,%22rawinventor_first_name%22,%22rawinventor_last_name%22,%22uspc_first_seen_date%22,%22uspc_last_seen_date%22,%22uspc_mainclass_id%22,%22uspc_mainclass_title%22,%22uspc_sequence%22,%22uspc_subclass_id%22,%22uspc_subclass_title%22,%22uspc_total_num_assignees%22,%22uspc_total_num_inventors%22,%22uspc_total_num_patents%22,%22wipo_field_id%22,%22wipo_field_title%22,%22wipo_sector_title%22,%22wipo_sequence%22]&o=%7B%22include_subentity_total_counts%22:false,%22matched_subentities_only%22:true,%22page%22:1,%22per_page%22:25%7D&s=

Meanwhile, this request (which only includes some of the fields shown above, doesn't result in an error:

http://www.patentsview.org/api/patents/query?q=%7B%22patent_number%22:%225116621%22%7D&f=[%22app_country%22,%22app_date%22,%22app_number%22,%22app_type%22,%22appcit_app_number%22,%22appcit_category%22,%22appcit_date%22,%22appcit_kind%22,%22appcit_sequence%22,%22assignee_city%22,%22assignee_country%22,%22assignee_county%22,%22assignee_county_fips%22]&o=%7B%22include_subentity_total_counts%22:false,%22matched_subentities_only%22:true,%22page%22:1,%22per_page%22:25%7D&s=

Any idea what's up? The first request shown above used to work.

**Comment by sarvothaman** [comment]
Hello,
Thanks for reporting the issue. We've fixed this now.
