### ISSUE TITLE
500 error on invalid field requests

### ISSUE THREAD

**Issue by mustberuss** [CSSIP-AIR/PatentsView-API#35]
The api is throwing a 500 error when an invalid field is requested. Ex:   [http://www.patentsview.org/api/patents/query?q={"patent_nbr":"9593152"}](http://www.patentsview.org/api/patents/query?q=%7B%22patent_nbr%22%3A%229593152%22%7D) Previously it threw a 400 and set the ultra helpful response header "X-Status-Reason": "Not a valid field for querying: patent_nbr"

**Comment by sarvothaman** [comment]
Hi, 
Thank you for reporting this issue. We are looking into a fix for this and will update this issue once it's fixed

Thanks!

**Comment by sarvothaman** [comment]
@mustberuss The query now throws 400 error with message when requesting patent_nbr. I am going to leave this ticket open for couple more days and close it if there are no follow ups. Thanks!

**Comment by mustberuss** [comment]
Looks good to me!  I am getting the 400 and seeing the X-Status-Reason header.  Thanks.
