### ISSUE TITLE
Odd query results

### ISSUE THREAD

**Issue by mustberuss** [CSSIP-AIR/PatentsView-API#44]
I'm seeing odd result, like that there is one patent issued in 2012.  Another user in the patentsview forum is reporting no results from a query that used to return results.  https://community.patentsview.org/forum/7/topic/156#comment-186

**Comment by sarvothaman** [comment]
@mustberuss Thanks for reporting this, we were able to fix this earlier today. Please verify if your queries are working now and let us know if you continue to see incorrect api results.

**Comment by mustberuss** [comment]
Looks good, thanks!
