### ISSUE TITLE
patent_id is missing from field list tables

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#46]
I'm able to retrieve patent_id from many of the API's endpoints, but this field isn't listed in any of the field list tables (e.g., https://www.patentsview.org/api/location.html). Wasn't sure if that omission was on purpose or not.

**Comment by sarvothaman** [comment]
Hello,
The patent_id and patent_number are synonymous. patent_id was originally intended to be an internal field to be used for joining different entities and patent_number to be used as the API field for the patent number. This is the reason for the lack of documentation on the field. While it is possible to query this field and while we don't have any plans for standardizing and de-duplicating API fields right now, I would wager that for any of the future standardization/cleanups, removing patent_id from the list of API fields would be a likely candidate.
