### ISSUE TITLE
POSTing results in error

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#49]
It appears as though POSTing to the API(s) is now resulting in errors. Using the GET method results in no such error.

``` r
library(httr)

endpoint <- 'https://www.patentsview.org/api/patents/query'
body <- '{"q":{"_gte":{"patent_date":"2007-01-04"}},"f":["patent_number","patent_date"]}'

response <- POST(endpoint, body = body)
content(response, "text")
#> [1] "{\"status\":\"error\",\"payload\":{\"error\":\"'q' param is missing\",\"code\":\"RQ1\"}}"
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Related to https://github.com/ropensci/patentsview/issues/21#issuecomment-687624142

**Comment by mustberuss** [comment]
@crew102 the endpoint now should be https://api.patentsview.org/patents/query then your code above works.  Gets get 301 redirects with the same url parameters.  On a post the body might not be getting sent to the new url, resulting in the "q param is missing" message. I saw the same behavior in posts in python too while gets worked.   If you could rebuild your R package with new endpoints it should all work.  Someone did post in the  [forum](https://community.patentsview.org/forum/7/topic/193) though saying they sometimes get an internal server error on posts with a lot of columns.  I didn't run the R package's tests but maybe you could.

**Comment by sarvothaman** [comment]
@crew102 & @mustberuss The server of the previous api does not suppot redirects where POST data is also redirected(only GET query paramters are redirected). In any case, the redirect is a failsafe for when people do not know about the change in URL. You should update the URL on all you applications as soon as you can. 

Please re-open or create new issues if you are still facing issues.
